# Python异步编程

## 协程与任务
[https://docs.python.org/zh-cn/3.7/library/asyncio-task.html](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html)

- 协程通过async/await语法声明，要运行协程，asyncio提供了三种机制
    - asyncio.run()

    - 等待一个协程

      ```python
      async def say_after(delay, what):
          await asyncio.sleep(delay)
          print(what)
      
      
      async def main():
          print(f'started at {time.strftime("%X")}')
      
          await say_after(1, 'hello')
          await say_after(2, 'world')
      
          print(f'finished at {time.strftime("%X")}')
      
      
      if __name__ == '__main__':
          asyncio.run(main())
      """
      started at 16:41:11
      hello
      world
      16:41:14
      finished at 16:41:14
      """
      ```
    - asyncio.create_task()用来并发执行多个多个协程

      ```python
      async def main2():
          task1 = asyncio.create_task(say_after(1, 'hello'))
          task2 = asyncio.create_task(say_after(2, 'world'))
      
          print(f'started at {time.strftime("%X")}')
          await task1
          await task2
          print(f'ended at {time.strftime("%X")}')
      ```

- 可等待对象：如果一个对象可以在await中使用，就是可等待对象。可等待对象主要分为三种主要类型：协程、任务和Future

  - 协程：协程函数(async def函数)  & 协程对象(调用协程函数返回的对象)

  - 任务：当一个协程通过asyncio.create_task()函数打包成一个任务，该协程将自动进入日程准备运行

    ```python
    async def nested():
        return 42
    
    
    async def main3():
        task = asyncio.create_task(nested())
        
        await task
    ```

  - Futures: 是一种特殊的低层级的可等待对象，表示一个异步操作的最终结果。在asyncio中需要future对象以便允许通过async/await使用基于回调的代码



## 并发运行任务

awaitable.asyncio.gather(*aws, loop=None, return_exceptions=False)

并发运行aws中可等待对象。如果所有可等待对象都成功完成，结果将是一个由所有返回值聚合而成的列表。结果值的顺序与 *aws* 中可等待对象的顺序一致。

如果 *return_exceptions* 为 `False` (默认)，所引发的首个异常会立即传播给等待 `gather()` 的任务。*aws* 序列中的其他可等待对象 **不会被取消** 并将继续运行。

如果 *return_exceptions* 为 `True`，异常会和成功的结果一样处理，并聚合至结果列表。

```python
async def factorial(name, number):
    f = 1
    for i in range(2, number+1):
        print(f'Task {name}: Compute factorial({i}...')
        await asyncio.sleep(1)
        f *= i
    print(f'Task {name}: factorial({number} = {f}')


async def main5():
    await asyncio.gather(
        factorial('A', 2),
        factorial('B', 3),
        factorial('C', 4)
    )
```

## 其他协程任务操作

- asyncio.shield(aw, *, loop=None)保护一个可等待对象防止被取消。如果包含它的协程被取消，shield保护的任务还会在执行，但是最终await表达式还是会抛出CancelledError。

  ```python
  res = await sheild(somethint())
  
  # 忽略取消操作
  try:
      res = await shield(something())
  except CancelledError:
      res = None
  ```

- asyncio.wait_for(aw, timeout, *, loop=None)指定timeout后超时，抛出TimeoutError错误。timeout为None时，会等待直到完成。

  ```python
  async def eternity():
      await asyncio.sleep(3600)
      print('ok!')
      
  
  async def main6():
      try:
          await asyncio.wait_for(eternity(), timeout=1)
      except asyncio.TimeoutError:
          print('timeout!')
  ```

- asyncio.wait(aws, *, loop=None, timeout=None, return_when=ALL_COMPLETED)运行aws指定的可等待对象并阻塞线层直到满足return_when的条件

  ```python
  async def foo():
      return 42
  
  
  async def main7():
      task = asyncio.create_task(foo())
      done, pending = await asyncio.wait({task})
  
      if task in done:
          print('finished')
  ```

- asyncio.as_complete(aws, *, loop=None, timeout=None)并发运行aws集合中可等待对象，返回一个Future对象的迭代器。

  ```python
  for f in as_completed(aws):
      earliest_result = await f
      # ...
  ```

## Task对象

[https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#asyncio.Task](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#asyncio.Task)

- 一个与 [`Future 类似`](https://docs.python.org/zh-cn/3.7/library/asyncio-future.html#asyncio.Future) 的对象，可运行 Python [协程](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#coroutine)。非线程安全
- Task 对象被用来在事件循环中运行协程。如果一个协程在等待一个 Future 对象，Task 对象会挂起该协程的执行并等待该 Future 对象完成。当该 Future 对象 *完成*，被打包的协程将恢复执行。

- 可以使用高层级的 [`asyncio.create_task()`](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#asyncio.create_task) 函数来创建 Task 对象，也可用低层级的 [`loop.create_task()`](https://docs.python.org/zh-cn/3.7/library/asyncio-eventloop.html#asyncio.loop.create_task) 或 [`ensure_future()`](https://docs.python.org/zh-cn/3.7/library/asyncio-future.html#asyncio.ensure_future) 函数。不建议手动实例化 Task 对象。

- 要取消一个正在运行的 Task 对象可使用 [`cancel()`](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#asyncio.Task.cancel) 方法。调用此方法将使该 Task 对象抛出一个 [`CancelledError`](https://docs.python.org/zh-cn/3.7/library/asyncio-exceptions.html#asyncio.CancelledError) 异常给打包的协程。
- [`cancelled()`](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#asyncio.Task.cancelled) 可被用来检测 Task 对象是否被取消。
- [`asyncio.Task`](https://docs.python.org/zh-cn/3.7/library/asyncio-task.html#asyncio.Task) 从 [`Future`](https://docs.python.org/zh-cn/3.7/library/asyncio-future.html#asyncio.Future) 继承了其除 [`Future.set_result()`](https://docs.python.org/zh-cn/3.7/library/asyncio-future.html#asyncio.Future.set_result) 和 [`Future.set_exception()`](https://docs.python.org/zh-cn/3.7/library/asyncio-future.html#asyncio.Future.set_exception) 以外的所有 API

## Future对象

[https://docs.python.org/zh-cn/3.7/library/asyncio-future.html](https://docs.python.org/zh-cn/3.7/library/asyncio-future.html)

- 一个Future代表一个异步运算的最终结果，线程不安全
- Future是一个可等待对象，协程可以等待Future对象直到他们有结果或异常集合或取消。

```python
async def set_after(fut: asyncio.Future, delay, value):
    await asyncio.sleep(delay)

    fut.set_result(value)


async def main8():
    loop = asyncio.get_running_loop()

    fut = loop.create_future()
    
    loop.create_task(set_after(fut, 1, '...world'))
    print('hello...')

    print(await fut)
```

## 事件循环

[https://docs.python.org/zh-cn/3.7/library/asyncio-eventloop.html](https://docs.python.org/zh-cn/3.7/library/asyncio-eventloop.html)

事件循环是每个 asyncio 应用的核心。 事件循环会运行异步任务和回调，执行网络 IO 操作，以及运行子进程。

### 获取事件循环

- asyncio.get_running_loop() 返回当前OS线程正在运行的事件循环，如果没有正在运行的事件循环会抛出RuntimeError。此函数只能由协程或回调来调用
- asyncio.get_event_loop() 推荐使用上面的get_running_loop()来获取事件循环
- asyncio.set_event_loop(loop) 将loop设置为当前OS线程的当前事件循环
- asyncio.new_event_loop() 创建一个新的事件循环

### 运行和停止循环

- loop.run_until_complete(future) 运行直到future被完成
- loop.run_forever() 运行事件循环直到stop()被调用
- loop.stop() 停止事件循环

### 调度回调

- loop.call_soon(callback, *args, context=None): 安排在下一次事件循环的迭代中使用args参数调用callback，回调按照注册顺序被调用，每个回调只被调用一次
- loop.call_soon_threadsafe(callback, *args, context=None): 线程安全的回调

### 调度延迟回调

- loop.call_later(delay, callback, *args, context=None): 安排回调在给定的delay后执行
- loop.call_at(when, callback, *args, context=None): 安排回调在给定的时间戳执行

## 创建Futures和Tasks

- loop.create_future() 创建一个附加到事件循环中的asyncio.Future对象
- loop.create_task(coro)安排一个协程的执行，返回task对象